added dry run test (#25)
* added dry run test

* fixed the skip_root but still need to work on

* replaced sudo with skip_root

* added counter to the number of dry-run test

* added du_cmd, changes upload to glance, and Hypervisor

* deleted run_cmd check_Hypervisor

* replaced run_cmd with TESTING_SKIP_ROOT_CHECK for checking bare_matal

* fixed spacing for TESTING_SKIP_ROOT_CHECK

* debuging the dry_run

* Added openstack installation on workflow

diff --git a/cc-snapshot b/cc-snapshot
--- a/cc-snapshot
+++ b/cc-snapshot
@@ -285,10 +285,13 @@ else
   OS_AUTH_URL=$(extract_json_key "auth_url_v3" "$JSON_VENDOR_DATA")
 fi
 
-if dmesg | grep -q Hypervisor; then
-  # The current instance is apparently not a baremetal node.
-  >&2 echo "Error: cc-snapshot is only supported for baremetal instances."
-  exit 1
+if  [[ -n "${TESTING_SKIP_ROOT_CHECK:-}" ]]; then 
+  echo "Skipping bare-metal check (requires root privileges)"
+else 
+  if dmesg | grep -q Hypervisor; then
+    echo "Error: cc-snapshot is only supported for baremetal instances." >&2
+    exit 1
+  fi
 fi
 
 export OS_REGION_NAME=$REGION
@@ -366,6 +369,17 @@ create_disk_image(){
 
   FS="ext4"
 
+  du_cmd=(du -d 0 -m --exclude-from="$EXCLUDE_FROM" /)
+  #dry-run stub for filesystem sizing
+  if [[ "$DRY_RUN" == true ]]; then
+    echo "[DRY_RUN] would measure filesystem size with:${du_cmd[*]} | awk '{print \$1}'"
+    filesystem_size=0
+    total_disk_size=1500
+  else
+    filesystem_size=$("${du_cmd[@]}" | awk '{print $1}')
+    total_disk_size=$((filesystem_size + 1500))
+  fi
+
   [[ -n ${LABEL:-} ]] || {
     LABEL="$(sudo e2label $(findmnt -t ext4 -J | jq -r ".filesystems[].source" ))"
     if [ ! -L "/dev/disk/by-label/$LABEL" ]; then
@@ -429,10 +443,6 @@ create_disk_image(){
   else
       extra_options="/dev/sda"
   fi
-
-  filesystem_size=$(du -d 0 -m --exclude-from=$EXCLUDE_FROM / |  awk -F" "  '{ print $1 }')
-  total_disk_size=$(($filesystem_size + 1500))
-
   # 550M for UEFI partition and 8M for BIOS partition
   run_cmd guestfish -N $CC_SNAPSHOT_CONVERTED_PATH=disk:"$total_disk_size"M -- \
   part-init /dev/sda gpt : \
@@ -453,19 +463,22 @@ create_disk_image(){
   # To complete the preparation of your snapshot image, create a compressed version of it:
   run_cmd qemu-img convert $CC_SNAPSHOT_CONVERTED_PATH -O $CC_SNAPSHOT_DISK_FORMAT $CC_SNAPSHOT_CONVERTED_COMPRESSED_PATH -c
 }
+
 ################################
 # Upload the Snapshot on Glance
 ################################
-
-# The final steps are to upload your snapshot image to OpenStack Glance.
 upload_to_glance(){
-  run_cmd openstack image create \
-  --disk-format $CC_SNAPSHOT_DISK_FORMAT \
-  --container-format bare \
-  $PROVENANCE_PROPERTIES \
-  $SNAPSHOT_NAME <$CC_SNAPSHOT_CONVERTED_COMPRESSED_PATH
-}
+  # build the command once
+  local CMD=(openstack image create --disk-format "$CC_SNAPSHOT_DISK_FORMAT" \
+              --container-format bare $PROVENANCE_PROPERTIES "$SNAPSHOT_NAME")
+  if [[ "$DRY_RUN" == true ]]; then
+    echo "[DRY_RUN] ${CMD[*]} < $CC_SNAPSHOT_CONVERTED_COMPRESSED_PATH"
+    return 0
+  fi
 
+  # perform the upload via stdin redirection
+  "${CMD[@]}" < "$CC_SNAPSHOT_CONVERTED_COMPRESSED_PATH"
+}
 install_prerequisites
 prepare_tarball
 check_size
