Fast-fail for auth, expand tilde in SSH key path

diff --git a/cc-snapshot b/cc-snapshot
--- a/cc-snapshot
+++ b/cc-snapshot
@@ -36,9 +36,9 @@ HOSTNAME=$(hostname)
 UUID=$(uuidgen)
 
 if [ $# -eq 0 ]; then
-    SNAPSHOT_NAME="${HOSTNAME}_${UUID}"
+  SNAPSHOT_NAME="${HOSTNAME}_${UUID}"
 else
-    SNAPSHOT_NAME="$1"
+  SNAPSHOT_NAME="$1"
 fi
 
 echo "Will snapshot the instance using the following name: '$SNAPSHOT_NAME'"
@@ -49,7 +49,7 @@ CENTOS='CentOS-Linux'
 
 UBUNTU_VERSION=''
 if [ $DISTRO = $UBUNTU ]; then
-    UBUNTU_VERSION=$(lsb_release -c | awk '{print $2}')
+  UBUNTU_VERSION=$(lsb_release -c | awk '{print $2}')
 fi
 
 #########################################################
@@ -65,113 +65,93 @@ fi
 # example: extract_json_key 'foo' '{"foo": 1, "bar": 2}'
 
 function extract_json_key {
-    RESULT=$(echo "$2" | sed "s/.*$1\": \"//g" | sed 's/".*//g')
-    echo "$RESULT"
+  RESULT=$(echo "$2" | sed "s/.*$1\": \"//g" | sed 's/".*//g')
+  echo "$RESULT"
 }
 
 JSON_VENDOR_DATA=$(curl -s http://169.254.169.254/openstack/latest/vendor_data.json)
 SITE=$(extract_json_key "site" "$JSON_VENDOR_DATA")
 
 if [ "$SITE" != "tacc" ] && [ "$SITE" != "uc" ]; then
-    # The current instance  is apparently not a baremetal node.
-    echo "ERROR: Could not understand which site you are using, please  be sure that you run the script inside a baremetal instance!"
-    exit 1
+  # The current instance  is apparently not a baremetal node.
+  echo "ERROR: Could not understand which site you are using, please  be sure that you run the script inside a baremetal instance!"
+  exit 1
 fi
 
 PROJECT_ID=$(extract_json_key "project_id" "$JSON_VENDOR_DATA")
 
-cat > /tmp/openrc <<- EOM
-#!/bin/bash
-
-# To use an OpenStack cloud you need to authenticate against the Identity
-# service named keystone, which returns a **Token** and **Service Catalog**.
-# The catalog contains the endpoints for all services the user/tenant has
-# access to - such as Compute, Image Service, Identity, Object Storage, Block
-# Storage, and Networking (code-named nova, glance, keystone, swift,
-# cinder, and neutron).
-#
-# *NOTE*: Using the 2.0 *Identity API* does not necessarily mean any other
-# OpenStack API is version 2.0. For example, your cloud provider may implement
-# Image API v1.1, Block Storage API v2, and Compute API v2.0. OS_AUTH_URL is
-# only for the Identity API served through keystone.
 export OS_AUTH_URL=https://chi.$SITE.chameleoncloud.org:5000/v2.0
-
-# With the addition of Keystone we have standardized on the term **tenant**
-# as the entity that owns the resources.
 export OS_TENANT_ID=$PROJECT_ID
-
-# In addition to the owning entity (tenant), OpenStack stores the entity
-# performing the action as the **user**.
-#echo "Please enter your Chameleon username: "
-#read -r OS_USERNAME_INPUT
-#export OS_USERNAME=\$OS_USERNAME_INPUT
-
-# With Keystone you pass the keystone password.
-#echo "Please enter your Chameleon password: "
-#read -sr OS_PASSWORD_INPUT
-#export OS_PASSWORD=\$OS_PASSWORD_INPUT
-
-# If your configuration has multiple regions, we set that information here.
-# OS_REGION_NAME is optional and only valid in certain environments.
 export OS_REGION_NAME="regionOne"
-# Don't leave a blank variable, unset it if it was empty
-if [ -z "\$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
-EOM
+if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
 
-# set +x
+if [ -z "$OS_USERNAME" ]; then
+  echo "Please enter your Chameleon username: "
+  read -r OS_USERNAME_INPUT
+  export OS_USERNAME=$OS_USERNAME_INPUT
+fi
 
-# Source the file that has been generated above
-source /tmp/openrc
+if [ -z "$OS_PASSWORD" ]; then
+  echo "Please enter your Chameleon password: "
+  read -sr OS_PASSWORD_INPUT
+  export OS_PASSWORD=$OS_PASSWORD_INPUT
+fi
 
-# set -x
+set +e
+glance image-list --limit=1 >/dev/null #2>&1
+if [ ! $? -eq 0 ]; then
+  echo Unable to contact Glance, check username and password
+  exit 1
+fi
+set -e
 
 #################################
 # Begin the snapshotting process
 #################################
 
 if [ $DISTRO = $CENTOS ]; then
-    # Install prerequisite software (only required for XFS file systems, which is the default on CentOS 7):
-    yum install -y libguestfs-xfs
-    yum update -y lvm2 # must be at least 2.02-171 to avoid bug https://bugzilla.redhat.com/show_bug.cgi?id=1475018
+  # Install prerequisite software (only required for XFS file systems, which is the default on CentOS 7):
+  yum install -y libguestfs-xfs
+  yum update -y lvm2 # must be at least 2.02-171 to avoid bug https://bugzilla.redhat.com/show_bug.cgi?id=1475018
 fi
 
 # Create a tar file of the contents of your instance:
 if [ "$UBUNTU_VERSION"=="xenial" ]; then
-   TAR_ARGS=""
+  TAR_ARGS=""
 else
-   TAR_ARGS="--xattrs"
+  TAR_ARGS="--xattrs"
 fi
 
 # The following code is inspired from http://unix.stackexchange.com/questions/82598
 n=0
 until [ $n -ge 5 ]
 do
-   tar cf /tmp/snapshot.tar / --selinux --acls $TAR_ARGS --numeric-owner --one-file-system  --exclude=/tmp/snapshot.tar --exclude=/tmp/* --exclude=/proc/* --exclude=/var/tmp/* --exclude=/boot/extlinux && break
-   n=$[$n+1]
-   sleep 15
+  tar cf /tmp/snapshot.tar / --selinux --acls $TAR_ARGS --numeric-owner --one-file-system  --exclude=/tmp/snapshot.tar --exclude=/tmp/* --exclude=/proc/* --exclude=/var/tmp/* --exclude=/boot/extlinux && break
+  n=$[$n+1]
+  sleep 15
 done
 
 if [ $DISTRO = $UBUNTU ]; then
-    if [ $UBUNTU_VERSION = "xenial" ]; then
+  if [ $UBUNTU_VERSION = "xenial" ]; then
     apt-get install -y libguestfs-tools
-    fi
+  fi
 
-    # Update guestfs appliances (prevent an error with virt-make-fs);
-    # BUG: one package cannot be found (kpartx) and cause update-guestfs-appliance
-    #      to exit with an error code;
-    apt-get -y update # APT repos may need an update in order to find kpartx
-    apt-get install -y kpartx
-    if [ "$(which update-guestfs-appliance)" != "" ]; then
-        update-guestfs-appliance || true
-    fi
+  # Update guestfs appliances (prevent an error with virt-make-fs);
+  # BUG: one package cannot be found (kpartx) and cause update-guestfs-appliance
+  #      to exit with an error code;
+  apt-get -y update # APT repos may need an update in order to find kpartx
+  apt-get install -y kpartx
+  if [ "$(which update-guestfs-appliance)" != "" ]; then
+    update-guestfs-appliance || true
+  fi
 
-    FS="ext4"
-    LABEL=`ls /dev/disk/by-label`
+  FS="ext4"
+  LABEL=`ls /dev/disk/by-label`
 fi
 
 if [ $DISTRO = $CENTOS ]; then
-    FS="xfs"
-    LABEL="img-rootfs"
+  FS="xfs"
+  LABEL="img-rootfs"
 fi
 
 ARCH=`uname -i`
@@ -186,24 +166,24 @@ fi
 # to the image, while what we (and Ironic) call partition images are images
 # without MBR, hence the inverted logic with the PARTITION_IMAGE variable.
 if [ "$PARTITION_IMAGE" == false ]; then
-    VIRT_MAKE_FS="virt-make-fs --partition"
+  VIRT_MAKE_FS="virt-make-fs --partition"
 else
-    VIRT_MAKE_FS="virt-make-fs"
+  VIRT_MAKE_FS="virt-make-fs"
 fi
 
 # This will take 3 to 5 minutes. Next, convert the tar file into a qcow2 image (if you don't want to use the XFS file system, you can replace xfs by ext4):
 $VIRT_MAKE_FS --format=qcow2 --type=$FS --label=$LABEL /tmp/snapshot.tar /tmp/snapshot.qcow2
 
 if [ "$PARTITION_IMAGE" == false ]; then
-    if [ $DISTRO = $CENTOS ]; then
-        # and looking at the name of the file in that directory. Next ensure that the GRUB bootloader is present in the image:
-        virt-customize -a /tmp/snapshot.qcow2 --run-command 'grub2-install /dev/sda && grub2-mkconfig -o /boot/grub2/grub.cfg'
-    fi
+  if [ $DISTRO = $CENTOS ]; then
+    # and looking at the name of the file in that directory. Next ensure that the GRUB bootloader is present in the image:
+    virt-customize -a /tmp/snapshot.qcow2 --run-command 'grub2-install /dev/sda && grub2-mkconfig -o /boot/grub2/grub.cfg'
+  fi
 
-    if [ $DISTRO = $UBUNTU ]; then
-        # Next ensure that the GRUB bootloader is present in the image:
-        guestfish -a /tmp/snapshot.qcow2 -i sh 'grub-install /dev/sda && grub-mkconfig -o /boot/grub/grub.cfg'
-    fi
+  if [ $DISTRO = $UBUNTU ]; then
+    # Next ensure that the GRUB bootloader is present in the image:
+    guestfish -a /tmp/snapshot.qcow2 -i sh 'grub-install /dev/sda && grub-mkconfig -o /boot/grub/grub.cfg'
+  fi
 fi
 
 # To remove unwanted configuration information from your image, run:
@@ -218,13 +198,13 @@ qemu-img convert /tmp/snapshot.qcow2 -O qcow2 /tmp/snapshot_compressed.qcow2 -c
 
 # The final steps are to upload your snapshot image to OpenStack Glance.
 if [ "$PARTITION_IMAGE" == false ]; then
-    glance image-create --name $SNAPSHOT_NAME --disk-format qcow2 --container-format bare < /tmp/snapshot_compressed.qcow2
+  glance image-create --name $SNAPSHOT_NAME --disk-format qcow2 --container-format bare < /tmp/snapshot_compressed.qcow2
 else
-    echo "You asked for a partition image."
-    echo "You will need to upload your kernel and ramdisk to Glance before uploading your image."
-    echo "You may want to run 'source /tmp/openrc' to set your OpenStack credentials."
-    echo "After kernel and ramdisk are uploaded, run:"
-    echo "glance image-create --name $SNAPSHOT_NAME --disk-format qcow2 --container-format bare --property kernel_id=IMAGE_VMLINUZ_UUID --property ramdisk_id=IMAGE_INITRD_UUID < /tmp/snapshot_compressed.qcow2"
+  echo "You asked for a partition image."
+  echo "You will need to upload your kernel and ramdisk to Glance before uploading your image."
+  echo "You may want to run 'source /tmp/openrc' to set your OpenStack credentials."
+  echo "After kernel and ramdisk are uploaded, run:"
+  echo "glance image-create --name $SNAPSHOT_NAME --disk-format qcow2 --container-format bare --property kernel_id=IMAGE_VMLINUZ_UUID --property ramdisk_id=IMAGE_INITRD_UUID < /tmp/snapshot_compressed.qcow2"
 fi
 
 exit 0
